language: node_js
node_js:
  - node # latest stable Node.js release
  - lts/* # latest LTS Node.js release
  - 8

# wait until after all node.js versions pass before deploying
# https://docs.travis-ci.com/user/build-stages/deploy-npm/

stages:
  - test
  - name: deploy
    if: tag IS present AND repo = 'nfriedly/set-cookie-parser'

jobs:
  include:
    - stage: deploy
      node_js: stable
      script: skip
      deploy:
        provider: npm
        email: nathan@nfriedly.com
        api_key:
          secure: "sZS9TjlBGdnKThzZLRhy3A3UN87FYcLoXDW2QdksLXe6vyt09W9OWFZuDdJOxFFsyr+M9G5whCSJM/eKq/ns7HtruqSVVEQQfgwsBARJMUhPV9RveMPbRyHy2LeaztVxrJsYwaV4F4cLJQpKcmGGjnPfp195Bq3XljFt2kQGvDVPWq+mhrW0Pz8rdKO5c9cGukXvcZga3YsHHkszERUo9b6bPTkPZfVhm+JEvhdhKT90CtCB291DvsEBEFcbV+S9aYjZvljCFeI5p5CoTF36hDKlAFY1Ya7/ZW6vMj8pL4lZ9bujAM9X5GfSzfj6HdEZm7UYmJjAJyxpJGZSou/Cf8HMiSskpkkwaK384Kv+nBCNtNvsK/qhCVgOv9rN7Re7ov74XHOwsF1sF4iE7yPbAUa8/gVgzncu/GI+wnfkud6WOlIH9F6sO43nQScwstXVLTogxmYrnTtw9efhL8pXCzG3lR9iTq49D9eV6dFHt2q1CIw0c9UCm1Y+XwqslrxYfgxsNThGqQDpZDlOBtwnzthAf0uu1akFmwRxDLpRlDVKXlHj/GOKcRpCwrKfau5agH1cKlkfKqi9BYepR3ROH3vcl4RklUUZUzD4QvSuYfwfIxKviOlZaipSjFzpi5V6oHRMCil41SavovCaNGmoOBqK8gO2Sz2CAuY76ab3Ljo="
        on:
          tags: true
          repo: nfriedly/set-cookie-parser
