language: node_js
node_js:
- 4
- 6
- 8
- 10
- stable

# wait until after all node.js versions pass before deploying
# https://docs.travis-ci.com/user/build-stages/deploy-npm/

stages:
  - test
  - name: tag
    if: type IS 'push' AND branch IS 'master' AND repo = 'nfriedly/express-rate-limit'
  - name: deploy
    if: tag IS present AND repo = 'nfriedly/express-rate-limit'

jobs:
  include:
    - stage: tag
      node_js: stable
      script: scripts/create_semver_tag.sh
    - stage: deploy
      node_js: stable
      script: skip
      deploy:
        provider: npm
        email: nathan@nfriedly.com
        api_key:
          secure: UQXR82XpBMROKVozdZiAPdFYvhOu56sp2n5U7ZMIe9+2i75f8KYa335Tdgx5OiZi8LJK6TwPCH5DG5kHgJm1iNvseIEEsn19gBzHxG4eezhCVwdz2C93eDBlNrcogTQn9aQ6YOqgiDkS9kd0TiMo0bu45LB8yMLTiiM1pN788nrrtULQVlCH1p2Xzwni0NAhfG6nxGI47dbLG6+LOo+ZE8lAkhPcuU7vQCtI5QQ7m2XLvzNiYoTzXGwBSN7Z5j10O/QO/lll/JWY3bS3yKL8+7zVqY2q7bno1VP2LVAB4A979OQxUeUi+5N99/BRa2GxHkodASZi/0NVAUEt5zk/G43GNUIuXA8Tfp6jXjBRJaTAAxwFJJd3qPZ5vVEDJ7g/RjHSV11FDNVL1PiIahnB2s4GRXcNQ/GvnfmfhifTzapjUGp21LW1yMlcTYiHXMsowwztFyVWFhzRnNzy8eCZRE0eSND6QLkJh1FoeQ6nNWqGXPeTVQMf4OGKiJ37EKwqt/BbHalWAJbnfDAxvP4cFAx2jj8nc+0BAT4a013QSQ+h/QFCfaz3mOPvkTcKSzQVzr9aqbE2yeiYwsJsh0BD38XqX6AsURfBFcIJ+zwCR6oZx+34UR57co3p5LE8OatgRZTTyCl+9znsjyRPG3vamgxP/5UrBbJr9c/mTBN/dBw=
        on:
          tags: true
          repo: nfriedly/set-cookie-parser
